<?php
/**
 * Created by IntelliJ IDEA.
 * User: nico
 * Date: 13/08/17
 * Time: 20:46
 */

namespace Clea\Form\Field;


use Clea\Form\Field;
use Clea\Form\FieldInterface;

class JsonField extends Field
{

    public function setValue($value): FieldInterface
    {
        if (is_iterable($value)) {
            return parent::setValue($value);
        } else {
            return parent::setValue(json_decode($value, true));
        }
    }

    public function getJson(){
        if (is_iterable($this->getValue())) {
            return json_encode($this->getValue());
        }
    }

    public function getValue()
    {
        return parent::getValue(); // TODO: Change the autogenerated stub
    }


}